# Generated by Django 3.0.5 on 2020-05-06 12:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('image', models.ImageField(upload_to='image')),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('wiki', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='debugger.User')),
                ('team_member', models.ManyToManyField(related_name='team_member', to='debugger.User')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='defect', max_length=80)),
                ('heading', models.CharField(max_length=100)),
                ('discription', models.CharField(default=' ', max_length=200)),
                ('media_uploads', models.CharField(default=' ', max_length=200)),
                ('reported_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debugger.Project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debugger.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=200)),
                ('Created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='debugger.User')),
                ('issue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debugger.Issue')),
                ('mentions', models.ManyToManyField(related_name='mentions', to='debugger.User')),
            ],
        ),
        migrations.CreateModel(
            name='Issue_assigned',
            fields=[
                ('issue_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='debugger.Issue')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='debugger.User')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to='debugger.User')),
            ],
        ),
    ]
