# Generated by Django 3.0.5 on 2020-05-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mention',
            field=models.ManyToManyField(related_name='mention', to='debugger.User'),
        ),
    ]
