# Generated by Django 3.0.5 on 2020-05-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='media_uploads',
            new_name='media_upload',
        ),
        migrations.AddField(
            model_name='issue',
            name='last_updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last Updated On'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('design', '1'), ('dev', '2'), ('UI', '3'), ('Ux', '4')], default='dev', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reported_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('reported', '1'), ('checked', '2'), ('solved', '3')], default='reported', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='debugger.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debugger.Issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mention',
            field=models.ManyToManyField(related_name='mentions', to='debugger.User'),
        ),
    ]
