# Generated by Django 3.0.5 on 2020-05-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0002_auto_20200519_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment',
            field=models.CharField(default=12345678, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
