# Generated by Django 3.0.5 on 2020-05-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0003_auto_20200520_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
