# Generated by Django 3.0.5 on 2020-05-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debugger', '0005_auto_20200520_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact',
        ),
    ]
